##### Pytorch 기본

In [ ]:
import torch
a = torch.tensor([1,2,3,4])
print(a)
print(type(a)) # 자료형 출력
print(a.shape)
print(a.dtype) # 데이터 타입 출력

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.Size([4])
torch.int64
1


In [10]:
A = torch.tensor([[1,2],[3,4]])
print(A.shape)
print(A.ndim) # 차원의수
print(A.numel()) # 전체 성분의 수 

torch.Size([2, 2])
2
4


In [22]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.ones_like(A))
print(torch.arange(0,10,3)) 
print(torch.arange(0,1,0.1))
print(torch.linspace(0,1,10)) # 0부터 1포함 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[1, 1],
        [1, 1]])
tensor([0, 3, 6, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [29]:
# 성분끼리 계산된다.
a=torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a+b)
print(a*b)
print(a**2)

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([1, 4, 9])


In [ ]:
# 행렬의곱
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[4,5,6],[7,8,9]])
print(A@B)

A = torch.randn(32,5,7)
B = torch.randn(32,7,5)
C = A@B
print(C.shape) # 채널마다 행렬곱 일어난다.

A = torch.randn(32,5,7)
B = torch.randn(7,5)
# print(A@B) -> 이렇게 해줘도 B의 차원이 32로 맞춰져서 계산된다(7,5)가 복제된다

tensor([[18, 21, 24],
        [40, 47, 54]])
torch.Size([32, 5, 5])
tensor([[[ 1.3641e+00,  6.1380e-01,  3.7259e+00,  1.1891e+00, -2.1779e-01],
         [ 2.8094e-02, -2.0703e+00,  1.3476e+00,  1.2185e-01,  8.0356e-01],
         [-2.3767e+00,  5.3744e+00, -3.4908e+00, -1.4278e+00, -3.9101e+00],
         [ 1.9338e+00, -1.5133e-01,  1.8297e+00, -3.7129e+00, -3.7633e+00],
         [ 1.2681e-01, -1.3535e+00,  1.2514e+00, -2.0734e+00, -2.0505e-01]],

        [[-1.7293e+00,  1.4303e+00, -6.7150e-01,  1.9565e+00, -4.3384e-01],
         [ 1.6273e+00, -2.1924e+00,  4.6547e+00, -2.8640e+00, -8.6260e-01],
         [ 1.3680e+00, -1.0091e+00,  2.4848e+00, -5.4322e-01,  6.8421e-01],
         [ 3.2673e-01,  1.4681e+00,  1.1903e+00, -4.1055e-02, -7.4173e-01],
         [ 1.8946e+00, -1.3715e+00,  4.0543e-01, -3.9200e+00,  4.8790e-01]],

        [[ 3.3493e+00, -3.2482e-01, -2.2478e+00, -5.5798e+00, -3.9077e+00],
         [ 2.8383e+00, -1.3455e+00,  1.0127e+00, -1.4632e+00, -1.6864e+00],
         [-5.500

#### pytorch의 인덱싱 슬라이스

In [ ]:
# 2차원 행렬에 대한 인덱싱과 슬라이싱
A = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])  # 하나만 쓰면 행에대한 인덱싱
print(A[1:]) # 헷갈렸던것

# 2개 같은 의미
print(A[1][2])
print(A[1,2])

print(A[0:3:2,2])

tensor([1, 2, 3])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor(6)
tensor(6)
tensor([3, 9])


In [47]:
A = torch.stack([ torch.arange(0,12).reshape(2,-1),
                 torch.arange(12,24).reshape(2,-1) ])
print(A)
print(A.shape)
print(A[0,1,2])

print(torch.tensor(4),torch.tensor(4).shape ) # 스칼라 텐서
print(torch.tensor([4]),torch.tensor([4]).shape) # 1차원 벡터 텐서
print(torch.tensor([[4]]),torch.tensor([[4]]).shape) # 2차원 행렬 텐서

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])
torch.Size([2, 2, 6])
tensor(8)
tensor(4) torch.Size([])
tensor([4]) torch.Size([1])
tensor([[4]]) torch.Size([1, 1])


In [64]:
# boolean 인덱싱
A=torch.arange(0,12).reshape(2,-1)
print(A)

B = A>=4
print(B)
print(A[B])

A[A>=4]=0
print(A)
print('--------------------------------')

A = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
B = torch.tensor([True,False,False,True])
print(A[B])
print(A[B,0])



tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True]])
tensor([ 4,  5,  6,  7,  8,  9, 10, 11])
tensor([[0, 1, 2, 3, 0, 0],
        [0, 0, 0, 0, 0, 0]])
--------------------------------
tensor([[1, 2],
        [7, 8]])
tensor([1, 7])


In [65]:
# 0:50 ~ 1:03은 일단 SKIP(추가적인 boolean 인덱싱 )

#### Pytorch의 여러 함수들

In [69]:
A = torch.randn(3,3) # Normal Distribition(평균0 ,분산1)
B = torch.rand(3,3)  # Uniform(0과1사이) 
print(A)
print(B)

tensor([[ 0.7884, -0.3634, -1.3905],
        [ 0.8925, -1.0260,  0.6824],
        [ 0.4488, -0.6079,  0.6641]])
tensor([[0.6857, 0.9979, 0.3107],
        [0.7539, 0.6049, 0.6544],
        [0.5010, 0.8996, 0.3464]])


In [74]:
print(torch.nan)
print(torch.inf)
print(torch.isnan(torch.tensor([torch.nan,1,2,torch.nan])))
print(torch.isinf(torch.tensor([torch.inf,1,2,torch.inf])))

nan
inf
tensor([ True, False, False,  True])
tensor([ True, False, False,  True])


In [ ]:
A = torch.randn(3,4)
print(A,A.shape)
print(torch.max(A))
print(torch.max(A,dim=0)) # dim은 선택한 축을 따라 데이터를 모아 하나의 대표값(예: 최대값)을 계산하고, 그 축은 결과 텐서에서 사라지며 나머지 축만 남는다.
print(torch.max(A,dim=0)[0].shape)
print('----------------------------------------')

# 이미지 배치일때
# (N, C, H, W) = (배치,채널,높이,너비)
A = torch.randn(10, 3, 32, 32) 
print(A.shape)
print(torch.max(A,dim=0)[0].shape) # 배치축 줄인다 -> 여러 장의 이미지를 합쳐서 대표 이미지를 만든다.
print(torch.max(A,dim=1)[0].shape) # 채널축 줄인다 -> RGB(3채널)를 하나로 합쳐서 픽셀별 대표 채널 값을 만든다.
print(torch.max(A,dim=2)[0].shape) 
print(torch.max(A,dim=3)[0].shape)
print('----------------------------------------')

# 비디오일떄
# (N, C, T, H, W) = (배치, 채널, 시간, 높이, 너비)
A = torch.randn(4, 3, 8, 32, 32) 
print(A.shape)  
print(torch.max(A,dim=2)[0].shape) # -> 시간축 줄인다 -> 비디오 전체를 표현하는 특징들

tensor([[ 0.5616, -0.3156, -1.7657, -1.3355],
        [ 0.5073,  0.9353, -0.3711, -0.4065],
        [-0.4246, -1.7379, -0.1917,  0.5669]]) torch.Size([3, 4])
tensor(0.9353)
torch.return_types.max(
values=tensor([ 0.5616,  0.9353, -0.1917,  0.5669]),
indices=tensor([0, 1, 2, 2]))
torch.Size([4])
----------------------------------------
torch.Size([10, 3, 32, 32])
torch.Size([3, 32, 32])
torch.Size([10, 32, 32])
torch.Size([10, 3, 32])
torch.Size([10, 3, 32])
----------------------------------------
torch.Size([4, 3, 8, 32, 32])
torch.Size([4, 3, 32, 32])


In [107]:
A = torch.randn(3,4)
print(A)
print(torch.argmax(A,dim=0)) # 인덱스 반환
# print('---------------------------------')
# a = torch.randn(6,1)
# print(a)
# print(torch.sort(a,dim=0)) # dim=1하면 안된다.

tensor([[ 1.9005, -0.5202,  0.3034,  0.5537],
        [-1.9189,  1.4483, -1.2180,  0.0486],
        [-0.1742, -0.8949,  0.4458,  0.2967]])
tensor([0, 1, 2, 0])


In [114]:
# reshape설명
A = torch.randint(1,5,size=(12,))
print(A)

B =A.reshape(2,2,3)
print(B)
print(B.reshape) # 차원의 마지막 부터 쌓는다. -> 여기선 (2,2,3)에서 3부터 쌓는다.

# transpose -> 3차원이상일땐 permute, 2차원일땐 .T사용
# 2차원일때
A = torch.randn(2,3)
print(A.shape)
print(A.T.shape)

# 3차원일때
A = torch.randn(4,3,6)
print(A.shape)
print(A.permute(0,2,1).shape)


tensor([4, 1, 3, 1, 2, 4, 3, 1, 4, 3, 4, 4])
tensor([[[4, 1, 3],
         [1, 2, 4]],

        [[3, 1, 4],
         [3, 4, 4]]])
<built-in method reshape of Tensor object at 0x7fca383112c0>
torch.Size([2, 3])
torch.Size([3, 2])
torch.Size([4, 3, 6])
torch.Size([4, 6, 3])


In [ ]:
# concat하는것
A = torch.ones((3,4))
B = torch.zeros((3,4))
print(torch.vstack([A,B])) # 세로로 쌓는다
print(torch.hstack([A,B])) # 가로로 쌓는다

print(torch.cat([A,B],dim=0))
print(torch.cat([A,B],dim=1))
print('--------------------')

A = torch.ones((2,3,4))
B = torch.zeros((2,3,4))

print(torch.cat([A,B],dim=0).shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
--------------------
torch.Size([4, 3, 4])


In [134]:
# sequeeze
A = torch.randn(1,1,3,1,4,1)
print(A.shape)
print(A.squeeze().shape)

# unsqueeze
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=6).shape)


# 활용
A = torch.randn((2,3))
B = torch.randn((2,3))
A = A.unsqueeze(dim=0)
B = B.unsqueeze(dim=0)
print(A.shape, B.shape)
print(torch.cat([A,B],dim=0).shape)

torch.Size([1, 1, 3, 1, 4, 1])
torch.Size([3, 4])
torch.Size([1, 1, 1, 3, 1, 4, 1])
torch.Size([1, 1, 3, 1, 4, 1, 1])
torch.Size([1, 2, 3]) torch.Size([1, 2, 3])
torch.Size([2, 2, 3])


In [139]:
# clone
A = torch.tensor([[1,2],[3,4]])
B = A.clone() # B=A  -> 이렇게 해주면 주소까지 같아진다.
B[0,0]=100
print(B)
print(A)

tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


In [147]:
# repeat -> 데이터를 복제해서 차원을 늘리는 것
A = torch.randn(32,5,7)
B = torch.randn(7,10)
B = B.repeat(32,1,1) # (32, 1, 1) -> 각 차원(dimension)을 몇 번 반복할 것인지 뜻한다.
print(B.shape)
# print(B[0,:,:]==B[1,:,:])
print('------------------------------------------')

A = torch.randn(2,3)
# print(A)
A = A.repeat(3,1,3,2)
# print(A)


torch.Size([32, 7, 10])
------------------------------------------


#### 딥러닝을 가능하게 한 autograd

In [156]:
x = torch.tensor([1.])
print(x)
print(x.requires_grad) # x.requires_grad=True로 바꿔줄수있음.

print('---------------------------')
x = torch.tensor([1.],requires_grad=True) # float이여야해서 1.로 해줌
print(x)
print(x.requires_grad)


tensor([1.])
False
---------------------------
tensor([1.], requires_grad=True)
True


In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x**2
print(x.grad)
y.backward() # 미분 수행
print(x.grad) # y를 x로 미분하고 값을 넣어준것이 x.grad에 있음.

None
tensor([2.])


In [168]:
# 변수가 1개일때
x = torch.tensor([1.], requires_grad=True)
y = x**2
z  = 3*y
# y.retain_grad() # -> 이거 해주면 y.grad볼수있다.
z.backward()

print(x.grad)
# print(y.grad)


tensor([6.])


In [172]:
# 변수가 여러개일때
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([1.], requires_grad=True)
z = 2*x**2+y**2
z.backward()
print(x.grad,y.grad)

tensor([4.]) tensor([2.])


In [174]:
x = torch.tensor([1., 2., 3.],requires_grad=True)
y = torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(x.grad)

tensor([2., 4., 6.])


In [181]:
# freeze시키기
# 방법1
x = torch.tensor([1.],requires_grad=True)
x.requires_grad = False
y = x**2
# y.backward() -> error!

# 방법2
x = torch.tensor([1.],requires_grad=True)
x = x.detach()
y=x**2
# y.backward() -> error!

In [ ]:
# chain rule위해 계속 grad_fu를 update하니까 grad_fn 잠시 계산 안하고 싶을때 torch.no_grad
# 모델 추론.평가 시에 불필요하게 메모리 안쓰게 한다.

x = torch.tensor([1.],requires_grad=True)
with torch.no_grad():
    y=x**2
    print(x.requires_grad) # requires_grad는 여전히 True이지만 
    print(y) # y에는 grad_fn이 없어서 역전파 대상이 아니다. 
print('-------------------')

y=x**2
y.backward()
print(y)

True
tensor([1.])
True
-------------------
tensor([1.], grad_fn=<PowBackward0>)


In [ ]:
print('할수있다!!')

####