#### 간단한 인공신경망 만들기

In [7]:
import torch
from torch import nn

x = torch.tensor([1.])
model = nn.Linear(1,1)

print(model.weight)
print(model.bias) 
print(x@model.weight + model.bias)
print(model(x))

Parameter containing:
tensor([[0.1522]], requires_grad=True)
Parameter containing:
tensor([-0.3568], requires_grad=True)
tensor([-0.2047], grad_fn=<AddBackward0>)
tensor([-0.2047], grad_fn=<ViewBackward0>)


In [ ]:
fc1 = nn.Linear(1,3) 
fc2 = nn.Linear(3,1)
model = nn.Sequential(fc1,fc2)


x = torch.tensor([1.])
print(model(x))

tensor([-0.4676], grad_fn=<ViewBackward0>)


In [12]:
model = nn.Sequential(nn.Linear(2,5),
                      nn.Linear(5,10),
                      nn.Linear(10,3))

x = torch.randn(10,2)
print(model(x),model(x).shape)

tensor([[-0.2804,  0.1510,  0.5917],
        [ 0.1086,  0.0501, -0.0817],
        [ 0.1466,  0.3324,  0.4366],
        [ 0.2266, -0.2171, -0.7592],
        [-0.1399,  0.1898,  0.4988],
        [ 0.4044,  0.1703, -0.2000],
        [-0.1794,  0.1248,  0.4168],
        [ 0.2779, -0.0052, -0.3976],
        [-0.0360,  0.0600,  0.1134],
        [ 0.2736,  0.0912, -0.1996]], grad_fn=<AddmmBackward0>) torch.Size([10, 3])


In [ ]:
class Mymodel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Sequential(nn.Linear(2,5),
                                    nn.Sigmoid(),
                                    nn.Linear(5,10),
                                    nn.Sigmoid(),
                                    nn.Linear(10,3),
                                    nn.Sigmoid())
    def forward(self,x):
        return self.linear(x)
        

x = torch.randn(10,2)
model = Mymodel()
print(model)
# print(model(x),model(x).shape)

# print(model.linear[0].weight) # Sequential은 인덱싱으로 접근
# print(model.linear[0].bias)

Mymodel(
  (linear): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=5, out_features=10, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=10, out_features=3, bias=True)
    (5): Sigmoid()
  )
)


In [30]:
# 모델의 파라미터 확인(모든 파라미터 나온다)
list(model.parameters()) # model.parameters() -> generate 타입 -> list로 바꿔주기

[Parameter containing:
 tensor([[-0.4893, -0.0060],
         [ 0.2623, -0.5406],
         [ 0.3057, -0.3842],
         [ 0.4652,  0.1766],
         [ 0.3615,  0.6504]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4979, -0.0480,  0.2036, -0.1692,  0.4375], requires_grad=True),
 Parameter containing:
 tensor([[-0.2389,  0.3624,  0.1842, -0.0657,  0.2403],
         [ 0.3750,  0.2970,  0.1061, -0.4301,  0.3442],
         [-0.3870,  0.2788,  0.2080,  0.0941,  0.2372],
         [ 0.1185, -0.3972,  0.1677,  0.4426,  0.0760],
         [ 0.0115,  0.4408, -0.1549, -0.2690,  0.0954],
         [ 0.3214,  0.1237,  0.0632,  0.1913, -0.3535],
         [-0.3949,  0.3340,  0.3241,  0.2220,  0.2089],
         [-0.4266,  0.1338,  0.3273, -0.4365,  0.3523],
         [ 0.2283, -0.3646,  0.2730, -0.4307, -0.4219],
         [ 0.3950,  0.1010, -0.3568,  0.3995,  0.1174]], requires_grad=True),
 Parameter containing:
 tensor([-0.2537, -0.2790,  0.3245,  0.1330, -0.1982,  0.4417, -0.4308,  0.0411,
  

In [31]:
# "학습" 파라미터 수 구하기
num = sum([p.numel() for p in model.parameters() if p.requires_grad])
print(num)

108


In [ ]:
# weight initialize하는건 넘어감

#### binary classification

In [ ]:
# (2) 1:23부터보기